//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalonEntities : DbContext
    {
        public SalonEntities()
            : base("name=SalonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Otvet> Otvet { get; set; }
        public virtual DbSet<Otziv> Otziv { get; set; }
        public virtual DbSet<Polzovatel> Polzovatel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tip_Master> Tip_Master { get; set; }
        public virtual DbSet<Tip_Polzovatel> Tip_Polzovatel { get; set; }
        public virtual DbSet<Tip_Tovar> Tip_Tovar { get; set; }
        public virtual DbSet<Tovar> Tovar { get; set; }
        public virtual DbSet<Variant> Variant { get; set; }
        public virtual DbSet<Vopros> Vopros { get; set; }
        public virtual DbSet<Zapis> Zapis { get; set; }
    }
}
