//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otvet
    {
        public int ID_Otvet { get; set; }
        public int ID_Variant { get; set; }
        public int ID_Polzovatel { get; set; }
    
        public virtual Polzovatel Polzovatel { get; set; }
        public virtual Variant Variant { get; set; }
    }
}
