//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otziv
    {
        public int ID_Otziv { get; set; }
        public string Napisanny_Otziv { get; set; }
        public Nullable<int> ID_Polzovatel { get; set; }
    
        public virtual Polzovatel Polzovatel { get; set; }
    }
}
