//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovatel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polzovatel()
        {
            this.Otvet = new HashSet<Otvet>();
            this.Otziv = new HashSet<Otziv>();
            this.Tovar = new HashSet<Tovar>();
            this.Zapis = new HashSet<Zapis>();
        }
    
        public int ID_Polzovatel { get; set; }
        public string Imya { get; set; }
        public string Phamilia { get; set; }
        public string Electronnya_Pochta { get; set; }
        public Nullable<long> Telephon { get; set; }
        public string Login { get; set; }
        public string Parol { get; set; }
        public int ID_Tip_Polzovatel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otvet> Otvet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otziv> Otziv { get; set; }
        public virtual Tip_Polzovatel Tip_Polzovatel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tovar> Tovar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapis> Zapis { get; set; }
    }
}
