//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int ID_Tovar { get; set; }
        public string Imya_Tovar { get; set; }
        public byte[] Photo_Tovar { get; set; }
        public int ID_Tip_Tovar { get; set; }
        public string Prais { get; set; }
        public string Opisanie_Tovar { get; set; }
        public int ID_Polzovatel { get; set; }
    
        public virtual Polzovatel Polzovatel { get; set; }
        public virtual Tip_Tovar Tip_Tovar { get; set; }
    }
}
