//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapis
    {
        public int ID_Zapis { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.TimeSpan> Vremya { get; set; }
        public Nullable<int> ID_Polzovatel { get; set; }
        public Nullable<int> ID_Master { get; set; }
        public Nullable<bool> Activien { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual Polzovatel Polzovatel { get; set; }
    }
}
