//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalonEntities : DbContext
    {
        public SalonEntities()
            : base("name=SalonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Otvet> Otvet { get; set; }
        public virtual DbSet<Otziv> Otziv { get; set; }
        public virtual DbSet<Polzovatel> Polzovatel { get; set; }
        public virtual DbSet<Tip_Master> Tip_Master { get; set; }
        public virtual DbSet<Tip_Polzovatel> Tip_Polzovatel { get; set; }
        public virtual DbSet<Tip_Tovar> Tip_Tovar { get; set; }
        public virtual DbSet<Tovar> Tovar { get; set; }
        public virtual DbSet<Variant> Variant { get; set; }
        public virtual DbSet<Vopros> Vopros { get; set; }
        public virtual DbSet<Zapis> Zapis { get; set; }
    }
}
