//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int ID_Tovar { get; set; }
        public string Imya_Tovar { get; set; }
        public byte[] Photo_Tovar { get; set; }
        public int ID_Tip_Tovar { get; set; }
        public string Prais { get; set; }
        public string Opisanie_Tovar { get; set; }
        public int ID_Polzovatel { get; set; }
        public string Srok_hranen { get; set; }
        public string Markirofka { get; set; }
        public string Uslovia_hranenya { get; set; }
    
        public virtual Polzovatel Polzovatel { get; set; }
        public virtual Tip_Tovar Tip_Tovar { get; set; }
    }
}
