//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapis
    {
        public int ID_Zapis { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.TimeSpan> Vremya { get; set; }
        public Nullable<int> ID_Polzovatel { get; set; }
        public Nullable<int> ID_Master { get; set; }
        public Nullable<bool> Activien { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual Polzovatel Polzovatel { get; set; }
    }
}
